[colors.bright]
black   = "#444b6a"
blue    = "#7da6ff"
cyan    = "#0db9d7"
green   = "#b9f27c"
magenta = "#bb9af7"
red     = "#ff7a93"
white   = "#acb0d0"
yellow  = "#ff9e64"

[colors.normal]
black   = "#32344a"
blue    = "#7aa2f7"
cyan    = "#449dab"
green   = "#9ece6a"
magenta = "#ad8ee6"
red     = "#f7768e"
white   = "#787c99"
yellow  = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[env]
TERM = "alacritty"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 1
y = 1

[scrolling]
history     = 10000
multiplier  = 3

[shell]
program ="/usr/bin/zsh"

[window]
dynamic_title   = true
opacity         = 0.6
title           = "Alacritty"

[window.class]
general     = "Alacritty"
instance    = "Alacritty"

[window.padding]
x = 6
y = 6

[debug]
persistent_logging = false
